{
    "name": "Hito EMU Custom Reports",
    "version": "18.0",
    "depends": ['l10n_ar', 'l10n_ar_stock','purchase_request','purchase_request_type'],
    "category": "",
    "summary": "Custom reports",
    "data": [
        'security/ir.model.access.csv',
        'views/account_move.xml',
        'views/stock_picking.xml',
        'views/sale_order_view.xml',
        'views/transporte.xml',
        'report/report.xml',
        'report/report_invoice_document.xml',
        'report/report_delivery_document.xml',
        'report/report_purchaseorder_document.xml',
    ],
    "installable": True,
    "application": False,
}